# Generated by Django 4.2.10 on 2024-02-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='cellPhone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
