# Generated by Django 4.2.10 on 2024-04-07 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='CEP',
            field=models.CharField(max_length=8, validators=[django.core.validators.MaxLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='users',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='idade',
            field=models.PositiveIntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='users',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
