# Generated by Django 4.2.10 on 2024-04-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_users_cep_alter_users_create_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='idade',
            field=models.PositiveIntegerField(),
        ),
    ]
