# Generated by Django 4.2.10 on 2024-04-07 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_users_idade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='idade',
            new_name='age',
        ),
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='users',
            name='cellPhone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.MaxLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='users',
            name='fullName',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
