# Generated by Django 4.2.10 on 2024-04-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_idade_users_age_alter_users_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='CEP',
            field=models.CharField(max_length=8),
        ),
    ]
