# Generated by Django 4.2.10 on 2024-04-07 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_users_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='CEP',
            field=models.CharField(max_length=8, validators=[django.core.validators.MaxLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MaxLengthValidator(99)]),
        ),
    ]
