# Generated by Django 4.2.10 on 2024-04-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_users_cep_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='CEP',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='cellPhone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='fullName',
            field=models.CharField(max_length=100),
        ),
    ]
