name: Run Dockerized Django App

on:
  push:
    branches:
      - main

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Construção da imagem Docker
        run: docker build -t tests .

      - name: Build and run Docker container
        run: docker-compose up --build -d

      - name: Inicialização do contêiner Docker
        run: docker run -d -p 80:8000 tests python manage.py runserver 0.0.0.0:8000

      - name: Wait for Django server to start
        run: sleep 10

      - name: Run tests
        run: docker-compose run web python manage.py test

      - name: Run Robot Tests
        run: docker-compose run web robot users/tests/functionalTests/tests_functional_post.robot
