name: Run Dockerized Django App

on:
  push:
    branches:
      - main

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      #- name: Construção da imagem Docker
       # run: docker build -t tests .

      - name: Build and run Docker container
        run: docker-compose up --build -d

      # - name: Inicialização do contêiner Docker
       # run: docker run -d -p 8000:8000 tests python manage.py runserver

      - name: Check if Docker server is accessible
        run: sleep 15

      - name: Run unit tests
        run: docker-compose exec web python manage.py test

      #- name: Run performance test
       # run: docker-compose run web pytest users/tests/performanceTests/tests_performance.py

      - name: Run Robot Functional Tests
        run: docker-compose exec web robot users/tests/functionalTests/

      - name: Run Robot Security Tests
        run: docker-compose exec web robot users/tests/securityTests/

