name: Run Dockerized Django App

on:
  push:
    branches:
      - main

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Docker container
        run: docker-compose up --build -d

      - name: Wait for Django server to start
        run: sleep 20

#      - name: Setup Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: '3.x'

#      - name: Install dependencies
#        run: pip install -r requirements.txt

      - name: Run tests
        run: docker-compose exec web python manage.py test

      - name: Run Robot Tests
        run: docker-compose exec web robot users/tests/functionalTests/tests_functional_post.robot
