name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  start_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Start Django server
        run: python manage.py runserver

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Wait for server to start
        run: sleep 15

      - name: Run tests
        run: python manage.py test

      - name: Run Robot Tests
        run: robot users/tests/functionalTests/tests_functional_post.robot

